# pgbouncer.ini

[databases]
* = host=localhost port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6000
auth_type = trust
auth_file = /app/.pgbouncer/users.txt
pool_mode = session
default_pool_size = 5
max_client_conn = 100
server_idle_timeout = 600
log_connections = 0
log_disconnections = 0