# Generated by Django 5.1.3 on 2024-12-22 19:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
                ('tiles', models.CharField(default='', max_length=50)),
                ('coins', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('dataWins', models.IntegerField(default=0)),
                ('dataLoss', models.IntegerField(default=0)),
                ('matchWins', models.IntegerField(default=0)),
                ('matchLoss', models.IntegerField(default=0)),
                ('lastTimeInSystem', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 19, 8, 34, 829098, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='DominoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_player', models.SmallIntegerField(default=-1)),
                ('board', models.CharField(blank=True, default='', max_length=200)),
                ('variant', models.CharField(choices=[('d6', 'Double 6'), ('d9', 'Double 9')], default='d6', max_length=10)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830295, tzinfo=datetime.timezone.utc))),
                ('winner', models.SmallIntegerField(default=-1)),
                ('scoreTeam1', models.IntegerField(default=0)),
                ('scoreTeam2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('wt', 'waiting_players'), ('ru', 'running'), ('ready', 'ready_to_play'), ('fi', 'finished'), ('fg', 'game_finished'), ('pa', 'paused')], default='wt', max_length=32)),
                ('maxScore', models.IntegerField(default=100)),
                ('inPairs', models.BooleanField(default=False)),
                ('perPoints', models.BooleanField(default=False)),
                ('startWinner', models.BooleanField(default=True)),
                ('lostStartInTie', models.BooleanField(default=False)),
                ('starter', models.SmallIntegerField(default=-1)),
                ('leftValue', models.SmallIntegerField(default=-1)),
                ('rightValue', models.SmallIntegerField(default=-1)),
                ('payPassValue', models.IntegerField(default=0)),
                ('payWinValue', models.IntegerField(default=0)),
                ('payMatchValue', models.IntegerField(default=0)),
                ('lastTime1', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830477, tzinfo=datetime.timezone.utc), null=True)),
                ('lastTime2', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830497, tzinfo=datetime.timezone.utc), null=True)),
                ('lastTime3', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830510, tzinfo=datetime.timezone.utc), null=True)),
                ('lastTime4', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830522, tzinfo=datetime.timezone.utc), null=True)),
                ('startAuto', models.IntegerField(blank=True, default=2, null=True)),
                ('sumAllPoints', models.BooleanField(default=False)),
                ('capicua', models.BooleanField(default=False)),
                ('rounds', models.SmallIntegerField(default=0)),
                ('moveTime', models.SmallIntegerField(default=10)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 22, 19, 8, 34, 830574, tzinfo=datetime.timezone.utc), null=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('days_active', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='dominoapp.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='dominoapp.player')),
                ('player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='dominoapp.player')),
                ('player4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='dominoapp.player')),
            ],
        ),
    ]
