# Generated by Django 5.0.6 on 2024-06-08 02:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0002_alter_player_options_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tiles',
            field=models.CharField(default=datetime.datetime(2024, 6, 8, 2, 5, 19, 823063, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DominoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_player', models.SmallIntegerField(default=-1)),
                ('board', models.TextField(max_length=200)),
                ('variant', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 6, 8, 2, 4, 50, 974041, tzinfo=datetime.timezone.utc))),
                ('left_side', models.SmallIntegerField(default=-1)),
                ('right_side', models.SmallIntegerField(default=-1)),
                ('winner', models.SmallIntegerField(default=-1)),
                ('scoreTeam1', models.IntegerField(default=0)),
                ('scoreTeam2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('wt', 'waiting_players'), ('ru', 'running')], max_length=32)),
                ('maxScore', models.IntegerField(default=100)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='dominoapp.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='dominoapp.player')),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='dominoapp.player')),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='dominoapp.player')),
            ],
        ),
    ]
