# Generated by Django 5.1.3 on 2025-01-08 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0003_alter_dominogame_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=10000)),
                ('created_coins', models.PositiveIntegerField(default=0)),
                ('extracted_coins', models.PositiveIntegerField(default=0)),
                ('buy_coins', models.PositiveIntegerField(default=0)),
                ('ads_coins', models.PositiveIntegerField(default=0)),
                ('datas_coins', models.PositiveIntegerField(default=0)),
                ('matches_coins', models.PositiveIntegerField(default=0)),
                ('private_tables_coins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65825, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65755, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65767, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65777, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime4',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65786, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65619, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastTimeInSystem',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 20, 4, 47, 65088, tzinfo=datetime.timezone.utc)),
        ),
    ]
