# Generated by Django 5.0.6 on 2024-07-01 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0005_alter_dominogame_board_alter_dominogame_left_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='inpairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='perPoints',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 27, 2, 642399, tzinfo=datetime.timezone.utc)),
        ),
    ]
