# Generated by Django 5.0.6 on 2024-07-03 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0006_dominogame_inpairs_dominogame_perpoints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominogame',
            old_name='inpairs',
            new_name='inPairs',
        ),
        migrations.AddField(
            model_name='dominogame',
            name='lostStartInTie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='startWinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='starter',
            field=models.SmallIntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 14, 21, 45, 48754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='status',
            field=models.CharField(choices=[('wt', 'waiting_players'), ('ru', 'running'), ('ready', 'ready_to_play'), ('fi', 'finished')], default='wt', max_length=32),
        ),
    ]
