# Generated by Django 5.0.6 on 2024-07-03 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0007_rename_inpairs_dominogame_inpairs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominogame',
            name='left_side',
        ),
        migrations.RemoveField(
            model_name='dominogame',
            name='right_side',
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 17, 14, 37, 959561, tzinfo=datetime.timezone.utc)),
        ),
    ]
