# Generated by Django 5.0.6 on 2024-08-04 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0008_remove_dominogame_left_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 14, 50, 2, 923856, tzinfo=datetime.timezone.utc)),
        ),
    ]
