# Generated by Django 5.0.6 on 2024-08-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0009_alter_dominogame_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='leftValue',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='rightValue',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 15, 23, 16, 25880, tzinfo=datetime.timezone.utc)),
        ),
    ]
