# Generated by Django 5.0.6 on 2024-08-09 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0010_dominogame_leftvalue_dominogame_rightvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 12, 20, 11, 613084, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='status',
            field=models.CharField(choices=[('wt', 'waiting_players'), ('ru', 'running'), ('ready', 'ready_to_play'), ('fi', 'finished'), ('fg', 'game_finished'), ('pa', 'paused')], default='wt', max_length=32),
        ),
    ]
