# Generated by Django 5.0.6 on 2025-04-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0011_status_transaction_alter_dominogame_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_transaction', to='dominoapp.dominogame'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rl', 'reload'), ('ex', 'extraction'), ('gm', 'game')], max_length=15, null=True),
        ),
    ]
