# Generated by Django 5.0.6 on 2024-08-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0012_alter_dominogame_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 14, 23, 11, 742529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiles',
            field=models.CharField(default='', max_length=50),
        ),
    ]
