# Generated by Django 5.0.6 on 2024-08-09 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0013_alter_dominogame_start_time_alter_player_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 6, 30, 163291, tzinfo=datetime.timezone.utc)),
        ),
    ]
