# Generated by Django 5.0.6 on 2025-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0013_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='board',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
