# Generated by Django 5.0.6 on 2024-08-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0014_alter_dominogame_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 16, 9, 465164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiles',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
