# Generated by Django 5.0.6 on 2025-04-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0014_alter_dominogame_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_transaction', to='dominoapp.dominogame'),
        ),
    ]
