# Generated by Django 5.0.6 on 2025-05-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from functools import partial

def add_user_player(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)
    UserModel = apps.get_model('auth', 'user')
    for obj in MyModel.objects.using(db_alias).all():
        if obj.user == None:
            user, create = UserModel.objects.get_or_create(
                email = obj.email if obj.email is not None else f"{obj.alias}@gmail.com",
                username = obj.alias,
                is_active = True
            )
            
            obj.user = user             
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0015_alter_transaction_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(partial(add_user_player, model_name='player'),reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
