# Generated by Django 5.0.6 on 2024-08-09 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0015_alter_dominogame_start_time_alter_player_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 20, 41, 535730, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiles',
            field=models.CharField(default='', max_length=50),
        ),
    ]
