# Generated by Django 5.0.6 on 2025-05-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0017_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
