# Generated by Django 5.0.6 on 2025-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0018_marketing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominogame',
            name='board',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
