# Generated by Django 5.0.6 on 2025-05-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0019_alter_dominogame_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rl', 'reload'), ('ex', 'extraction'), ('gm', 'game'), ('pro', 'promotion')], max_length=15, null=True),
        ),
    ]
