# Generated by Django 5.0.6 on 2024-08-26 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0020_alter_dominogame_lasttime1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='rounds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 26, 12, 46, 59, 498071, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 26, 12, 46, 59, 498071, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 26, 12, 46, 59, 498071, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime4',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 26, 12, 46, 59, 498071, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 12, 46, 59, 498071, tzinfo=datetime.timezone.utc)),
        ),
    ]
