# Generated by Django 5.0.6 on 2025-06-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0021_appversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='coins',
            new_name='earned_coins',
        ),
        migrations.AddField(
            model_name='player',
            name='recharged_coins',
            field=models.IntegerField(default=0),
        ),
    ]
