# Generated by Django 5.0.6 on 2025-06-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0022_rename_coins_player_earned_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inactive_player',
            field=models.BooleanField(default=False),
        ),
    ]
