# Generated by Django 5.0.6 on 2025-06-11 13:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0023_player_inactive_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+{1}?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_user', to='dominoapp.player'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='descriptions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
