# Generated by Django 5.0.6 on 2025-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0024_player_phone_transaction_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tiles',
            field=models.CharField(default='', max_length=50),
        ),
    ]
