# Generated by Django 5.0.6 on 2025-06-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0025_alter_player_tiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_players', to='dominoapp.player')),
                ('player_blocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_players', to='dominoapp.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='blockplayer',
            constraint=models.UniqueConstraint(fields=('player_blocker', 'player_blocked'), name='player_can_only_block_other_player_once'),
        ),
    ]
