# Generated by Django 5.0.6 on 2025-06-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0026_blockplayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.BigIntegerField()),
                ('board_in_game', models.CharField(blank=True, max_length=500, null=True)),
                ('board_left', models.SmallIntegerField(blank=True, null=True)),
                ('board_right', models.SmallIntegerField(blank=True, null=True)),
                ('player_alias', models.CharField(max_length=50)),
                ('player_tiles', models.CharField(max_length=50)),
                ('tile_move', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('play_automatic', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_played', to='dominoapp.dominogame')),
                ('player_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_move', to='dominoapp.player')),
                ('players_in_game', models.ManyToManyField(related_name='active_player', to='dominoapp.player')),
                ('transactions_list', models.ManyToManyField(blank=True, related_name='transaction_for_movement', to='dominoapp.transaction')),
            ],
        ),
    ]
