# Generated by Django 5.0.6 on 2024-10-10 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0027_player_lasttimeinsystem_alter_dominogame_lasttime1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='payMatchValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 21, 6, 15, 757600, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 21, 6, 15, 757600, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 21, 6, 15, 757600, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime4',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 21, 6, 15, 757600, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 21, 6, 15, 756587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastTimeInSystem',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 21, 6, 15, 755078, tzinfo=datetime.timezone.utc)),
        ),
    ]
