# Generated by Django 5.0.6 on 2025-06-26 16:44

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0027_moveregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateTimeField(blank=True, null=True, verbose_name='Referral Date')),
                ('referral_code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', length=6, max_length=7, prefix='', unique=True, verbose_name='Referral Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('code_date', models.DateTimeField(auto_now_add=True, verbose_name='Code Date')),
                ('reward_granted', models.BooleanField(default=False, verbose_name='Reward Granted')),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='dominoapp.player', verbose_name='Referred User')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='dominoapp.player', verbose_name='Referrer')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-code_date'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
