# Generated by Django 5.0.6 on 2025-07-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0028_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveregister',
            name='player_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moveregister',
            name='score_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moveregister',
            name='score_team2',
            field=models.IntegerField(default=0),
        ),
    ]
