# Generated by Django 5.1.3 on 2024-11-20 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0028_dominogame_paymatchvalue_alter_dominogame_lasttime1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dataLoss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dataWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matchLoss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matchWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 20, 21, 33, 39, 386511, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 20, 21, 33, 39, 386526, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 20, 21, 33, 39, 386537, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='lastTime4',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 20, 21, 33, 39, 386547, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='moveTime',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dominogame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 21, 33, 39, 386367, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastTimeInSystem',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 21, 33, 39, 385810, tzinfo=datetime.timezone.utc)),
        ),
    ]
