# Generated by Django 5.0.6 on 2025-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0029_moveregister_player_points_moveregister_score_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
