# Generated by Django 5.0.6 on 2025-07-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0029_moveregister_player_points_moveregister_score_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.URLField(),
        ),
    ]
