# Generated by Django 5.0.6 on 2025-07-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0030_alter_appversion_version_alter_player_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.URLField(),
        ),
    ]
