# Generated by Django 5.0.6 on 2025-07-29 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0032_alter_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pago pendiente'), ('paid', 'pago completado'), ('canceled', 'pago cancelado')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia'), ('paypal', 'pago por paypal')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payment', to='dominoapp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_payment', to='dominoapp.player')),
                ('status_list', models.ManyToManyField(blank=True, related_name='status_payment', to='dominoapp.status_payment')),
            ],
        ),
    ]
