# Generated by Django 5.0.6 on 2025-08-14 23:39

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models
import shortuuid
from functools import partial

def add_referral_code(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)
    
    for obj in MyModel.objects.using(db_alias).all():
        exist = MyModel.objects.using(db_alias).filter(referral_code = obj.referral_code).exclude(id=obj.id).exists()
        if exist:
            obj.referral_code = shortuuid.random(length=6)
            obj.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0034_rename_datas_coins_bank_game_coins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.AddField(
            model_name='player',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to='dominoapp.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='referral_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', db_index=True, length=6, max_length=7, prefix='', verbose_name='Referral Code'),
        ),
        migrations.RunPython(partial(add_referral_code, model_name='player'),reverse_code=migrations.RunPython.noop),
    ]
