# Generated by Django 5.0.6 on 2025-08-15 01:34

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0035_player_parent_player_referral_code_delete_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='referral_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', db_index=True, length=6, max_length=7, prefix='', unique=True, verbose_name='Referral Code'),
        ),
    ]
