# Generated by Django 5.0.6 on 2025-08-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0036_alter_player_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reward_granted',
            field=models.BooleanField(default=False, verbose_name='Reward Granted'),
        ),
    ]
