# Generated by Django 5.0.6 on 2025-08-21 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0037_player_reward_granted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('referrer_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_player', to='dominoapp.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
