# Generated by Django 5.0.6 on 2025-08-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0038_referralplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia'), ('paypal', 'pago por paypal'), ('zelle', 'pago por zelle')], max_length=32, null=True),
        ),
    ]
