# Generated by Django 5.0.6 on 2025-09-17 18:50

from django.db import migrations, models
from functools import partial

def update_table_no(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)
    no = 1
    for obj in MyModel.objects.using(db_alias).all().order_by('id'):
        obj.table_no = no
        obj.save()
        no+=1

class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0040_bankaccount_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(partial(update_table_no, model_name='dominogame'),reverse_code=migrations.RunPython.noop),
        
    ]
