# Generated by Django 5.0.6 on 2025-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0041_dominogame_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
