# Generated by Django 5.0.6 on 2025-09-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0041_remove_dominogame_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagame',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datas', to='dominoapp.matchgame'),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player1', to='dominoapp.player'),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player2', to='dominoapp.player'),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player3', to='dominoapp.player'),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player4', to='dominoapp.player'),
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='domino_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='dominoapp.dominogame'),
        ),
    ]
