# Generated by Django 5.0.6 on 2025-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0042_alter_player_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='description',
            field=models.TextField(),
        ),
    ]
