# Generated by Django 5.0.6 on 2025-09-26 12:55

from django.db import migrations, models
from functools import partial


def update_delete_email(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)

    for obj in MyModel.objects.using(db_alias).filter(inactive_player = True):
        obj.inactive_player = False
        obj.send_delete_email = True
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0043_alter_appversion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='send_delete_email',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(partial(update_delete_email, model_name='player'),reverse_code=migrations.RunPython.noop),

    ]
