# Generated by Django 5.0.6 on 2025-10-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0044_player_send_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('rate_exchange', models.DecimalField(decimal_places=6, default=0.0, max_digits=11)),
                ('inverce_rate_exchange', models.DecimalField(decimal_places=6, default=0.0, max_digits=11)),
            ],
        ),
    ]
