# Generated by Django 5.0.6 on 2025-10-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0045_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='inverce_rate_exchange',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=11, null=True),
        ),
    ]
