# Generated by Django 5.0.6 on 2025-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0046_alter_currencyrate_inverce_rate_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rl', 'reload'), ('ex', 'extraction'), ('gm', 'game'), ('pro', 'promotion'), ('tr', 'transfer')], max_length=15, null=True),
        ),
    ]
