# Generated by Django 5.0.6 on 2025-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0047_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='transfer_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
