# Generated by Django 5.0.6 on 2025-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0048_bank_transfer_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_transaction',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('ip', 'in_process'), ('cp', 'completed'), ('cc', 'canceled')], default='p', max_length=32),
        ),
    ]
