# Generated by Django 5.0.6 on 2025-11-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0049_alter_status_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
