# Generated by Django 5.0.6 on 2025-11-18 03:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dominoapp', '0050_transaction_whatsapp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_game', models.IntegerField(default=1)),
                ('games_win_team_1', models.IntegerField(default=0)),
                ('games_win_team_2', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_game', to='dominoapp.dominogame')),
                ('pair_list', models.ManyToManyField(related_name='pairs_in_game', to='dominoapp.player')),
                ('player_list', models.ManyToManyField(related_name='players_in_game', to='dominoapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_1', to='dominoapp.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_2', to='dominoapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_place_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('second_place_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('third_place_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('winner_payout', models.IntegerField(default=0)),
                ('second_payout', models.IntegerField(default=0)),
                ('third_payout', models.IntegerField(default=0)),
                ('registration_fee', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, help_text='%d-%m-%Y %H:%M:%S')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, help_text='%d-%m-%Y %H:%M:%S')),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wt', 'waiting_players'), ('ready', 'ready_to_play'), ('ru', 'running'), ('tf', 'finished'), ('pa', 'paused')], default='wt', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament_no', models.IntegerField(blank=True, null=True)),
                ('variant', models.CharField(choices=[('d6', 'Double 6'), ('d9', 'Double 9')], default='d6', max_length=10)),
                ('maxScore', models.IntegerField(default=100)),
                ('inPairs', models.BooleanField(default=True)),
                ('startWinner', models.BooleanField(default=False)),
                ('moveTime', models.SmallIntegerField(default=10)),
                ('min_player', models.IntegerField(default=8)),
                ('place_content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dominoapp'), ('model', 'player')), models.Q(('app_label', 'dominoapp'), ('model', 'pair')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player_list', models.ManyToManyField(related_name='player_list', to='dominoapp.player')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(default=1)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('game_list', models.ManyToManyField(related_name='games_in_round', to='dominoapp.dominogame')),
                ('pair_list', models.ManyToManyField(related_name='pairs_in_round', to='dominoapp.pair')),
                ('player_list', models.ManyToManyField(related_name='players_in_round', to='dominoapp.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_in_tournament', to='dominoapp.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='dominogame',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_in_tournament', to='dominoapp.tournament'),
        ),
    ]
