# Generated by Django 5.0.6 on 2025-11-25 04:25

from django.db import migrations
from functools import partial

def restar_elo(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)

    for obj in MyModel.objects.using(db_alias).all():
        obj.elo = 1500
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0052_player_elo_player_lat_player_lng'),
    ]

    operations = [
        migrations.RunPython(partial(restar_elo, model_name='player'),reverse_code=migrations.RunPython.noop),
    ]
