# Generated by Django 5.0.6 on 2025-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0053_auto_20251124_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='timezone',
            field=models.CharField(default='America/Havana', max_length=50),
        ),
    ]
