# Generated by Django 5.0.6 on 2025-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0053_auto_20251124_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='tournament_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='timezone',
            field=models.CharField(default='America/Havana', max_length=50),
        ),
        migrations.AddField(
            model_name='round',
            name='winner_pair_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='winner_pairs_in_round', to='dominoapp.pair'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_player',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='tournament',
            name='notification_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='notification_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='notification_5',
            field=models.BooleanField(default=False),
        ),
    ]
