# Generated by Django 5.0.6 on 2025-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0054_bank_tournament_coins_player_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_game',
            name='pair_list',
            field=models.ManyToManyField(related_name='pairs_in_game', to='dominoapp.pair'),
        ),
    ]
