# Generated by Django 5.0.6 on 2025-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0055_alter_match_game_pair_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
