# Generated by Django 5.0.6 on 2025-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0056_alter_round_round_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_match_win',
            field=models.IntegerField(default=2),
        ),
    ]
