# Generated by Django 5.0.6 on 2026-01-16 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0057_tournament_number_match_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='last_notifications',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='notifications_players_send',
            field=models.ManyToManyField(blank=True, help_text='Jugadores que ya han sido notificados sobre esta mesa', null=True, related_name='notify_players', to='dominoapp.player'),
        ),
    ]
