# Generated by Django 5.0.6 on 2026-01-17 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0058_dominogame_last_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominogame',
            name='last_notifications',
        ),
        migrations.RemoveField(
            model_name='dominogame',
            name='notifications_players_send',
        ),
        migrations.AddField(
            model_name='player',
            name='last_notifications',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
