# Generated by Django 5.0.6 on 2026-01-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0059_remove_dominogame_last_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_game',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_round', to='dominoapp.round'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default="torneo de prueba", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='player_list', to='dominoapp.player'),
        ),
    ]
