# Generated by Django 5.0.6 on 2026-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0060_match_game_round_tournament_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin_amount', models.PositiveIntegerField(default=0)),
                ('paymentmethod', models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia'), ('paypal', 'pago por paypal'), ('zelle', 'pago por zelle')], max_length=32, null=True)),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
    ]
