# Generated by Django 5.0.6 on 2026-02-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0061_packagecoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='package_coins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_payment', to='dominoapp.packagecoins'),
        ),
    ]
