# Generated by Django 5.0.6 on 2026-02-02 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from functools import partial
from datetime import datetime, timedelta

def update_sumary(apps, schema_editor, model_name):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('dominoapp', model_name)
    summary = apps.get_model('dominoapp', 'summaryplayer')

    first_day = datetime.now().replace(day=1, hour=0, minute=0, second=0)
    print("first_day: ", first_day )
    for obj in MyModel.objects.using(db_alias).all():
        summary.objects.create(
            player = obj,
            created_at = first_day,
            data_wins = obj.dataWins,
            data_loss = obj.dataLoss,
            match_wins = obj.matchWins,
            match_loss = obj.matchLoss
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0062_payment_package_coins'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='SummaryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_wins', models.PositiveIntegerField(default=0)),
                ('data_loss', models.PositiveIntegerField(default=0)),
                ('data_tie', models.PositiveIntegerField(default=0)),
                ('match_wins', models.PositiveIntegerField(default=0)),
                ('match_loss', models.PositiveIntegerField(default=0)),
                ('tournament_wins', models.PositiveIntegerField(default=0)),
                ('tournament_loss', models.PositiveIntegerField(default=0)),
                ('pass_player', models.PositiveIntegerField(default=0)),
                ('owner_pass', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_player', to='dominoapp.player')),
            ],
        ),
        
        migrations.RunPython(partial(update_sumary, model_name='player'),reverse_code=migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='player',
            name='dataLoss',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dataWins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matchLoss',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matchWins',
        ),
    ]
