# Generated by Django 5.0.6 on 2026-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0063_remove_player_dataloss_remove_player_datawins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='send_game_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
