# Generated by Django 5.0.6 on 2026-02-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0064_player_send_game_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryplayer',
            name='tournament_loss',
        ),
    ]
