# Generated by Django 5.0.6 on 2026-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0065_remove_summaryplayer_tournament_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryplayer',
            name='earned_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='loss_coins',
            field=models.IntegerField(default=0),
        ),
    ]
