# Generated by Django 5.0.6 on 2026-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0066_summaryplayer_earned_coins_summaryplayer_loss_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sumAllPoints',
            field=models.BooleanField(default=False),
        ),
    ]
