# Generated by Django 5.0.6 on 2026-02-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0068_chatroom_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_type', models.CharField(max_length=50)),
                ('date_of_week', models.IntegerField(blank=True, null=True)),
                ('date_of_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='summaryplayer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_66_game',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_99_game',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_by_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_in_pairs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_in_single',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='play_without_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rl', 'reload'), ('ex', 'extraction'), ('gm', 'game'), ('pro', 'promotion'), ('tr', 'transfer'), ('rw', 'reward')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transaction', to='dominoapp.playerreward'),
        ),
    ]
