# Generated by Django 5.0.6 on 2026-03-02 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0069_playerreward_alter_summaryplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lastTimeInGame',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
