# Generated by Django 5.0.6 on 2026-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0070_player_lasttimeingame'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerreward',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
