# Generated by Django 5.0.6 on 2026-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0071_playerreward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerreward',
            name='place',
            field=models.IntegerField(default=1),
        ),
    ]
