# Generated by Django 5.0.6 on 2026-03-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0073_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('CUP', 'Pesos Cubanos'), ('USD', 'Dolar')], default='CUP', max_length=4),
        ),
    ]
