# Generated by Django 5.0.6 on 2026-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0074_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
