# Generated by Django 5.0.6 on 2026-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0075_alter_notification_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='send_in_pair_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='send_invitation_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
