# Generated by Django 5.0.6 on 2026-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0076_player_send_in_pair_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='notification_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
