# Generated by Django 5.0.6 on 2026-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0077_tournament_notification_deadline'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dominogame',
            index=models.Index(fields=['player1'], name='idx_game_player1_notnull'),
        ),
        migrations.AddIndex(
            model_name='dominogame',
            index=models.Index(fields=['status'], name='idx_game_status'),
        ),
        migrations.AddIndex(
            model_name='dominogame',
            index=models.Index(fields=['status', 'id'], name='idx_game_status_id'),
        ),
        migrations.AddIndex(
            model_name='dominogame',
            index=models.Index(fields=['tournament'], name='idx_game_tournament'),
        ),
    ]
