# Generated by Django 5.0.6 on 2026-03-19 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dominoapp', '0078_dominogame_idx_game_player1_notnull_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['isPlaying'], name='idx_player_is_playing'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['lastTimeInSystem'], name='idx_player_last_system'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['tournament', '-round_no'], name='idx_round_tourn_no'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['active'], name='idx_tournament_active'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['active', 'status'], name='idx_tourn_active_status'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_at'], name='idx_tournament_start_at'),
        ),
    ]
