# Generated by Django 5.0.6 on 2026-04-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0079_player_idx_player_is_playing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryplayer',
            name='free_data_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_data_tie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_data_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_match_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_match_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_owner_pass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryplayer',
            name='free_pass_player',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
