# Generated by Django 5.0.6 on 2026-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0080_summaryplayer_free_data_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('rl', 'reload'), ('ex', 'extraction'), ('gm', 'game'), ('pro', 'promotion'), ('pro_mov', 'promotion by movie'), ('tr', 'transfer'), ('rw', 'reward')], max_length=15, null=True),
        ),
    ]
