# Generated by Django 5.0.6 on 2026-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0081_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_game',
            name='type_game',
            field=models.CharField(choices=[('normal', 'Ronda Normal / Clasificatoria'), ('final', 'Gran Final (1er y 2do Lugar)'), ('third', 'Definición de 3er Lugar')], default='normal', max_length=10),
        ),
    ]
