# Generated by Django 5.0.6 on 2026-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0083_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
