# Generated by Django 5.0.6 on 2026-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0085_alter_manager_users_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominogame',
            name='min_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='start_coins',
            field=models.IntegerField(default=0),
        ),
    ]
