# Generated by Django 5.0.6 on 2026-08-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0086_dominogame_min_fee_player_start_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecoins',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia'), ('paypal', 'pago por paypal'), ('zelle', 'pago por zelle'), ('google', 'pago por google')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('saldo', 'saldo movil'), ('transferencia', 'transferencia'), ('paypal', 'pago por paypal'), ('zelle', 'pago por zelle'), ('google', 'pago por google')], max_length=32, null=True),
        ),
    ]
