# Generated by Django 5.0.6 on 2026-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0087_alter_packagecoins_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominogame',
            old_name='min_fee',
            new_name='max_coins',
        ),
        migrations.AddField(
            model_name='dominogame',
            name='max_datas',
            field=models.IntegerField(default=0),
        ),
    ]
