# Generated by Django 5.0.6 on 2026-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0088_rename_min_fee_dominogame_max_coins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('web', 'Web')], default='web', max_length=20),
        ),
    ]
