# Generated by Django 5.0.6 on 2026-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominoapp', '0089_alter_round_options_player_country_player_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('fcm_message', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('players', models.ManyToManyField(related_name='players_list', to='dominoapp.player')),
            ],
        ),
    ]
